name: CI
on:
  push:
    branches: [ "Main-List" ]
  pull_request:
    branches: [ "Main-List" ]
    schedule:
        - cron: '25 4 * * 4,6'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: wget -i Action-link.txt
