name: Check App Links
on:
  schedule:
      - cron: '0 0 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DownApps.yml
        run: wget -i Action-link.txt
