name: CI
on:
  push:
    branches: [ "Main-List" ]
  pull_request:
    branches: [ "Main-List" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DownApps.yml
        run: wget -i Action-link.txt
