- name: main-list
  # You may pin to the exact commit or the version.
  # uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4
  uses: urlstechie/urlchecker-action@0.0.34
  with:
    # A project to clone. If not provided, assumes already cloned in the present working directory.
    git_path: # optional
    # A subfolder to parse instead of the root directory.
    subfolder: # optional
    # Force pass of checking, regardless of the result.
    force_pass: # optional
    # If a project (git_path) is defined, use this branch. Defaults to master
    branch: # optional, default is master
    # Cleanup (delete) repository to check after doing so (appropriate for when clone is done)
    cleanup: # optional
    # A comma seperated list of paths or patterns to include.
    include_files: # optional, default is 
    # A comma-separated list of file types to cover in the URL checks
    file_types: # optional, default is .md,.py,.rst,.html
    # Choose whether to include file with no URLs in the prints.
    print_all: # optional
    # Choose whether to print a more verbose end summary with files and broken URLs.
    verbose: # optional
    # Run in serial (good for debugging)
    serial: # optional
    # If a request fails, retry this number of times. Defaults to 1
    retry_count: # optional, default is 1
    # A csv file path to save the results to.
    save: # optional, default is 
    # The timeout (seconds) to provide to requests to wait for a response.
    timeout: # optional, default is 5
    # A comma seperated links to exclude during URL checks.
    exclude_urls: # optional, default is 
    # A comma seperated patterns to exclude during URL checks.
    exclude_patterns: # optional, default is 
    # A comma seperated list of paths or patterns to exclude during URL checks.
    exclude_files: # optional, default is 
    # Number of workers to run in parallel (defaults to 9)
    workers: # optional
